version: '2'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - "3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  redis-master:
    container_name: redis-master
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - .:/app
  redis-slave:
    container_name: redis-slave
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    volumes:
       - .:/app
  web:
    image: drupal:latest
    volumes: 
      - ./sites:/var/www/html/sites
    ports:
      - "8080:80"
    links:
      - redis-master
      - redis-slave
      - db
